version: "3"
services:
    #  elasticsearch:
    #    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    #    environment:
    #      - bootstrap.memory_lock=true
    #      - discovery.type=single-node
    #      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    #      - ELASTIC_PASSWORD=VerySecret
    #      - xpack.security.enabled=false
    #      - xpack.security.transport.ssl.enabled=false
    #      - xpack.security.http.ssl.enabled=false
    #      - KIBANA_PASSWORD=VerySecret
    #    ulimits:
    #      memlock:
    #        soft: -1
    #        hard: -1
    #    ports:
    #      - "9200:9200"
    #    networks: ["stack"]

    #  kibana:
    #    image: docker.elastic.co/kibana/kibana:8.12.1
    #    environment:
    #      - ELASTICSEARCH_USERNAME=kibana_system
    #      - ELASTICSEARCH_PASSWORD=VerySecure
    #    ports: ["5601:5601"]
    #    networks: ["stack"]
    #    links: ["elasticsearch"]
    #    depends_on: ["elasticsearch"]

    redis:
        image: "redis:7.2.4"
        ports:
            - "6379:6379"

networks:
    stack: {}
