name: Deploy

on:
    push:
        branches: [master]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2 # Ensures we can check the last commit message
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  registry: registry.toming.cz
                  username: stejs
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: master

            - name: Build
              uses: docker/build-push-action@v3
              with:
                  context: ./
                  tags: registry.toming.cz/logger:latest
                  push: true

            - name: Send deploy signal
              uses: fjogeleit/http-request-action@v1
              with:
                  url: "https://controller.toming.cz/container/logger/update"
                  method: "POST"
                  bearerToken: ${{ secrets.CONTROLLER_API_KEY }}
